import { Inter } from 'next/font/google'
import './globals.css'
import Header from "./component/Header";
import Nav from "./component/Nav";
// import Footer from "./component/Footer";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header/>
        <Nav />
        <div className="main-container">
          {children}
        </div>
        {/* <Footer/> */}
      </body>
    </html>
  )
}
